source/glest_game/ai/ai_interface.cpp, source/glest_game/ai/ai_interface.h, source/glest_game/game/game.cpp, source/glest_game/game/game.h, source/glest_game/game/game_constants.h, source/glest_game/menu/menu_state_connected_game.cpp, source/glest_game/menu/menu_state_connected_game.h, source/glest_game/menu/menu_state_custom_game.cpp, source/glest_game/menu/menu_state_join_game.cpp, source/glest_game/network/client_interface.cpp, source/glest_game/network/client_interface.h, source/glest_game/network/network_message.cpp, source/glest_game/network/network_message.h, source/glest_game/network/server_interface.cpp, source/glest_game/network/server_interface.h, source/glest_game/world/map.cpp, source/glest_game/world/map.h
This only puts the text "Observer" on the connected client's menu.
=> [wip] change how observer mode works (#13)

source/glest_game/ai/ai.cpp, source/glest_game/ai/ai.h, source/glest_game/ai/ai_rule.cpp, source/glest_game/ai/ai_rule.h
Second attempt at upgrading the AI.
=> Made changes to the AI; hopefully upgrades!

AUTHORS.md
=> Included MathuSum Mut and Keith Sammut

source/glest_game/types/command_type.cpp, source/glest_game/types/command_type.h, source/glest_game/types/damage_multiplier.cpp, source/glest_game/types/damage_multiplier.h, source/glest_game/types/element_type.cpp, source/glest_game/types/element_type.h, source/glest_game/types/faction_type.cpp, source/glest_game/types/faction_type.h, source/glest_game/types/object_type.cpp, source/glest_game/types/object_type.h, source/glest_game/types/projectile_type.cpp, source/glest_game/types/projectile_type.h, source/glest_game/types/resource_type.cpp, source/glest_game/types/resource_type.h, source/glest_game/types/skill_type.cpp, source/glest_game/types/skill_type.h, source/glest_game/types/tech_tree.cpp, source/glest_game/types/tech_tree.h, source/glest_game/types/tileset_model_type.cpp, source/glest_game/types/tileset_model_type.h, source/glest_game/types/unit_type.cpp, source/glest_game/types/unit_type.h, source/glest_game/types/upgrade_type.cpp, source/glest_game/types/upgrade_type.h
`indent -i2 -nut -bl -bli0 -ppi3 -nce -npsl`
=> types:reformat/style

source/glest_game/type_instances/unit.cpp
I think this will help until #48 is straightened out.
See Also: #8
=> unit.cpp:revert default right-click to move

source/glest_game/menu/menu_state_connected_game.cpp, source/glest_game/menu/menu_state_custom_game.cpp, source/glest_game/menu/menu_state_custom_game.h, source/glest_game/world/map.cpp, source/shared_lib/include/map/map_preview.h, source/shared_lib/sources/map/map_preview.cpp
Making progress
I did my changes on the wrong branch. I'm closing the PR I had open for this (#24)
I'm tired.
=> [wip #13] enhanced observer mode additions and cleanup [skip ci]

source/glest_game/menu/menu_state_masterserver.cpp
Remove MG_ and _NNN from Players List but not inside chat, that is for another day.
=> Remove MG_ and _NNN from Players List

source/glest_game/menu/menu_state_masterserver.cpp
Make sure that the _nnn suffix is always 3 digits
=> Make sure that the _nnn suffix is always 3 digits

ChangeLog.md
Added 5 entries going back to March 14th, 2018.
Did I miss anything?
=> changelog:update [skip ci]

source/shared_lib/include/platform/posix/ircclient.h, source/shared_lib/sources/platform/posix/ircclient.cpp
Most of these changes don't do anything, but near L820 in ircclient.cpp,
there was an extra "g"
Also changed the header
=> ircclient:change spelling

source/glest_game/graphics/renderer.cpp
This is recent patch @titiger made for @MegaGlest in
https://github.com/MegaGlest/megaglest-source/commit/1caed4acccb90a10dfef3d21ca5f0651daf8a918
=> render resources of selected faction in observer mode

WEBSITE_DESIGN.md
=> WEBSITE_DESIGN.md: add files that aid testing for master-server changes

source/glest_game/menu/menu_state_custom_game.h
Fixes ?
https://scan4.coverity.com/reports.htm#v10064/p15637/g10064g/fileInstanceId=50222844&defectInstanceId=9301921&mergedDefectId=317047&eventId=9301921-3
=> menu_state_custom_game.h:init 'index'

source/shared_lib/sources/platform/posix/ircclient.cpp
displays message like this.
```<ZG_andy_400> has joined```
=> ircclient.cpp:add joinAnnounce message

mk/linux/glest.ini, mk/macos/glest.ini, mk/windows/glest.ini, mk/windows/glest_release.ini, source/glest_game/global/core_data.cpp, source/glest_game/global/core_data.h
This closes #113 and will help with #110
=> put filenames back into source code

.travis.yml
=> .travis.yml:add tests for 'make install'

BUILD.md, INSTALL.md, README.md
=> final reviewing and editing

.travis.yml, BUILD.md, source/tests/CMakeLists.txt
=> .travis.yml:add c++11 flag for osx

ChangeLog.md, source/shared_lib/CMakeLists.txt, source/shared_lib/sources/compression/compression_utils.cpp, source/shared_lib/sources/miniz/ChangeLog.md, source/shared_lib/sources/miniz/LICENSE, source/shared_lib/sources/miniz/miniz.c, source/shared_lib/sources/miniz/miniz.h, source/shared_lib/sources/miniz/miniz_common.h, source/shared_lib/sources/miniz/miniz_tdef.c, source/shared_lib/sources/miniz/miniz_tdef.h, source/shared_lib/sources/miniz/miniz_tinfl.c, source/shared_lib/sources/miniz/miniz_tinfl.h, source/shared_lib/sources/miniz/miniz_zip.c, source/shared_lib/sources/miniz/miniz_zip.h, source/shared_lib/sources/miniz/readme.md
Update [miniz](https://github.com/richgel999/miniz) library. Thanks
to @richgel999 and the miniz contributors.
=> shared_lib/miniz:update miniz library

BUILD.md, INSTALL.md
=> BUILD.md:typo (mk->mkdir)

mk/linux/simulate_lag.txt
This may help with testing  (#90) (#150) [skip ci]
=> simulate_lag.txt:add doc for simulating lag

README.md
=> Blog readme

README.md
=> Fix typo (scenarious)

AUTHORS.md, mk/linux/setupBuildDeps.sh, packaging/debian/control
Work on issue https://github.com/ZetaGlest/zetaglest-source/issues/265
Removed all references to libxml as needed.
=> Removed unneeded refrences to libxml

source/glest_game/ai/ai_rule.cpp
Added some documentation for a couple functions I understood.
=> Added documentation for AiRuleRepair::getMinUnitsToRepairCastle() and AiRuleAddTasks::execute()

source/glest_game/ai/ai.cpp
As part of issue #276 add code comments for AI work.
=> Add code comments in ai.cpp
